/**
 * Canonical action types written to ActivityLog.
 * Group these by domain so the timeline UI can filter consistently.
 */
export enum ActivityAction {
  // Students
  STUDENT_CREATED = 'STUDENT_CREATED',
  STUDENT_UPDATED = 'STUDENT_UPDATED',
  STUDENT_DELETED = 'STUDENT_DELETED',
  STUDENT_GPA_CHANGED = 'STUDENT_GPA_CHANGED',
  STUDENT_ASSIGNED_MENTOR = 'STUDENT_ASSIGNED_MENTOR',
  STUDENT_ASSIGNED_TUTOR = 'STUDENT_ASSIGNED_TUTOR',

  // Achievements
  ACHIEVEMENT_UPLOADED = 'ACHIEVEMENT_UPLOADED',
  ACHIEVEMENT_APPROVED = 'ACHIEVEMENT_APPROVED',
  ACHIEVEMENT_REJECTED = 'ACHIEVEMENT_REJECTED',
  ACHIEVEMENT_REVISION_REQUESTED = 'ACHIEVEMENT_REVISION_REQUESTED',

  // Attendance
  ATTENDANCE_RECORDED = 'ATTENDANCE_RECORDED',
  ATTENDANCE_BULK_RECORDED = 'ATTENDANCE_BULK_RECORDED',

  // Assignments
  ASSIGNMENT_RECORDED = 'ASSIGNMENT_RECORDED',
  ASSIGNMENT_PLAGIARISM_FLAGGED = 'ASSIGNMENT_PLAGIARISM_FLAGGED',

  // Tutor evaluations
  TUTOR_EVALUATION_RECORDED = 'TUTOR_EVALUATION_RECORDED',

  // Penalties
  PENALTY_ADDED = 'PENALTY_ADDED',
  PENALTY_REMOVED = 'PENALTY_REMOVED',

  // Recovery
  RECOVERY_ASSIGNED = 'RECOVERY_ASSIGNED',
  RECOVERY_COMPLETED = 'RECOVERY_COMPLETED',
  RECOVERY_REJECTED = 'RECOVERY_REJECTED',

  // Employment
  EMPLOYMENT_SUBMITTED = 'EMPLOYMENT_SUBMITTED',
  EMPLOYMENT_APPROVED = 'EMPLOYMENT_APPROVED',

  // KPI
  KPI_RECALCULATED = 'KPI_RECALCULATED',
  SCHOLARSHIP_STATUS_CHANGED = 'SCHOLARSHIP_STATUS_CHANGED',
}
